### PR TITLE
Update bioservices to v1.11.2

### PR DESCRIPTION
**Pull request by mencian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mencian** [comment]
@conda-forge-admin, please rerender

**Comment by mencian** [comment]
Hello @hadim, can I trouble you for a review when you get a chance? I've also added myself to the recipe maintainers section.

**Comment by hadim** [comment]
LGTM. I removed myself as maintainer.

**Comment by hadim** [comment]
@conda-forge-admin, please rerender

**Comment by hadim** [comment]
@mencian you should close the other PRs.

**Comment by mencian** [comment]
It seems the autotick-bot recognized that a newer version now exists and automatically closed the previous PRs. Thank you for responding so quickly!

**Pull request merged**
